name: 🐞 Bug Report
description: Report an issue with the project
labels: ["bug"]
body:
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: 🐛 Describe the Bug
      description: A concise description of the issue you are experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✔️ Expected Behavior
      description: Describe what you expected to happen.
    validations:
      required: true
  - type: textarea
    attributes:
      label: 👣 Steps to Reproduce
      description: Steps to reproduce the issue.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 🖥️ Operating System
      description: Which operating system are you using?
      options:
        - label: Windows
        - label: macOS
        - label: Linux
        - label: Other
  - type: input
    id: software-version
    attributes:
      label: 🛠️ Software Version
      description: What version of the software are you using?
      placeholder: "e.g. v1.0.0"
    validations:
      required: true
  - type: textarea
    attributes:
      label: ✍️ Additional Context
      description: |
        Any other information, links, or context that would help understand the issue.
        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false